# use dedicated builder image to keep final image clean/small
# 1. copy python distribution from build context into image
# 2. install open3e from local distribution in venv, so that the venv can easily be copied to the final image
FROM python:3.12-alpine3.20 AS builder
RUN apk update && apk add --no-cache git
RUN pip install git+https://github.com/open3e/open3e.git

FROM python:3.12-alpine3.20

COPY --from=builder /open3e /open3e

WORKDIR /open3e

COPY run.sh /run.sh
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]
