# use dedicated builder image to keep final image clean/small
# 1. copy python distribution from build context into image

FROM python:3.12-alpine3.20 AS builder
RUN apk update && apk add --no-cache git

WORKDIR /open3e

RUN python -m venv /open3e/.venv && source /open3e/.venv/bin/activate
RUN pip install git+https://github.com/open3e/open3e.git

FROM python:3.12-alpine3.20

COPY --from=builder /open3e /open3e

COPY run.sh /
RUN chmod a+x /run.sh

WORKDIR /open3e

ENV PYTHONUNBUFFERED=1
ENV PATH="/open3e/.venv/bin:$PATH
CMD [ "/run.sh" ]
